name: Test site

on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install --no-cache-dir -r requirements.txt
      - run: mkdocs build --strict --verbose --site-dir test